#! /bin/bash
#  Supervise managing messages via queue
#  Last modified: 2016-10-31

RQ=/usr/local/bin/rq
WORKER=worker
CONFIG=goodcrypto.mail.message_queue_settings
LOG=/var/local/log/goodcrypto/goodcrypto.mail.message_queue_settings.log

sudo -u goodcrypto $RQ $WORKER --quiet --config $CONFIG &>$LOG
