#! /usr/bin/python
'''
    Copyright 2015 GoodCrypto
    Last modified: 2015-08-14
'''
import os, sh, sys
from traceback import format_exc

# limit the path to known locations
os.environ['PATH'] = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

from goodcrypto.oce.key.gpg_plugin import GPGPlugin
from syr.log import get_log

log = get_log()


def main():
    ''' Check GPG's trust DB. '''

    log('starting check')

    try:
        GPGPlugin().check_trustdb()
    except:
        log(format_exc())

    log('finished check')


if __name__ == "__main__":
    main()
    sys.exit(0)

