'''
    Constants for GoodCrypto app.

    Copyright 2014 Good Crypto
    Last modified: 2015-01-06
'''

import os, os.path

# set this to False to ship, True to test
# consider changing this to something easier to understand 
WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP = False
if WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP:
    WARNING = 'WARNING! WARNING! WARNING! TESTING ONLY! DO NOT SHIP!'
    
PROJECT = 'GoodCrypto'
GOODCRYPTO_VERSION = '0.9'

BASE_PROJECT_DIR = '/var/local/projects'
SHORT_NAME = PROJECT.lower()
PROJECT_DIR = os.path.join(BASE_PROJECT_DIR, SHORT_NAME)
GOODCRYPTO_DATA_DIR = os.path.join(PROJECT_DIR, 'server', 'data')

VM_NAME = 'GoodCrypto Server apps'
# find the goodcrypto virtual box so we'll know the VM owner
VM_OWNER = PROJECT.lower()  # set a default
# scripts generated by dBuild go here
VM_SCRIPT_DIR = os.path.join(os.path.dirname(__file__), 'vms')

HOME_ROOT = '/home'
home_dirs = os.listdir(HOME_ROOT)
for home_dir in home_dirs:
    server_filename = os.path.join(HOME_ROOT, home_dir, 'VirtualBox VMs', VM_NAME)
    if os.path.exists(server_filename):
        VM_OWNER = home_dir
        break

# domain or ip of the system running the hypervisor
VM_HOST = '127.0.0.1'
HTTP_PROXY_PORT = 8398
HTTP_PROXY_URL = 'http://{}:{}'.format(VM_HOST, HTTP_PROXY_PORT)

TOR_PORT = 9151     # tails privoxy
# TOR_PORT = 9050   # tor default
# TOR_PORT = 9063   # tails tor


if WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP:
    FORWARDED_APP_SSH_PORT = 8022
    FORWARDED_HOST_SSH_PORT = 8122
    FORWARDED_MAILSERVER_SSH_PORT = 8222

