'''
    Constants for GoodCrypto app.

    Copyright 2014-2015 GoodCrypto
    Last modified: 2015-01-25
'''

import os, os.path

# set this to False to ship, True to test
# consider changing this to something easier to understand
WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP = False
if WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP:
    WARNING = 'WARNING! WARNING! WARNING! TESTING ONLY! DO NOT SHIP!'

PROJECT = 'GoodCrypto'
FULL_PROJECT_NAME = '{} Private Server'.format(PROJECT)
ISO_NAME = '{}.iso'.format(FULL_PROJECT_NAME.lower().replace(' ', '_'))

BASE_PROJECT_DIR = '/var/local/projects'
SHORT_NAME = PROJECT.lower()
PROJECT_DIR = os.path.join(BASE_PROJECT_DIR, SHORT_NAME)
GOODCRYPTO_DATA_DIR = os.path.join(PROJECT_DIR, 'server', 'data')

VM_NAME = 'GoodCrypto Private Server'
# find the goodcrypto virtual box so we'll know the VM owner
VM_OWNER = PROJECT.lower()  # set a default
# scripts generated by dBuild go here
VM_SCRIPT_DIR = os.path.join(os.path.dirname(__file__), 'vms')

HOME_ROOT = '/home'
try:
    home_dirs = os.listdir(HOME_ROOT)
    for home_dir in home_dirs:
        server_filename = os.path.join(HOME_ROOT, home_dir, 'VirtualBox VMs', VM_NAME)
        if os.path.exists(server_filename):
            VM_OWNER = home_dir
            break
except:
    pass

# domain or ip of the system running the hypervisor
VM_HOST = '127.0.0.1'
HTTP_PROXY_PORT = 8398
HTTP_PROXY_URL = 'http://{}:{}'.format(VM_HOST, HTTP_PROXY_PORT)

TOR_PORT = 9350

if WARNING_WARNING_WARNING_TESTING_ONLY_DO_NOT_SHIP:
    FORWARDED_APP_SSH_PORT = 8022
    FORWARDED_HOST_SSH_PORT = 8122
    FORWARDED_MAILSERVER_SSH_PORT = 8222

HTTP_PORT = 8080
HTTPS_PORT = 8443

POSTFIX_FILTER_PORT = 10025

# apps status
STATUS_GREEN = 'green'
STATUS_RED = 'red'
STATUS_YELLOW = 'yellow'

# tor status file
TOR_STATUS_FILE = '/tmp/goodcrypto.tor.status'

# name for the databases
DEFAULT_DB = 'default'
MAIL_DB = DEFAULT_DB #'mail'
SYSTEM_DB = 'system'
WEB_DB = 'web'

# unique 'goodcrypto' user id used as base for other user ids
# project start date 2013-07-01 --> 1371
DEFAULT_USER_ID = 1371

# timestamp when ISO was created
TIMESTAMP_DIR = '/var/lib/goodcrypto'
TIMESTAMP_FILENAME = '{}.timestamp'.format(ISO_NAME)
TIMESTAMP_PATH = os.path.join(TIMESTAMP_DIR, TIMESTAMP_FILENAME)

